[metadata]
format.version = "1.1"


[versions]
assertj = "3.24.2"
awaitility = "4.2.0"
jupiter = "5.9.3"
openTelemetry = "1.18.0"
restAssured = "5.3.0"
rsApi = "3.1.0"


[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
jakarta-rsApi = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "rsApi" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }
opentelemetry-annotations = { module = "io.opentelemetry:opentelemetry-extension-annotations", version.ref = "openTelemetry" }
restAssured = { module = "io.rest-assured:rest-assured", version.ref = "restAssured" }


[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }